### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by GitKing-Wu** [YuyangYin/CLEDiffusion#11]
Hello, Thank you for sharing. In the image enhancement task, do the final enhancement results use GT like LLFlow when calculating PSNR with GT?

**Comment by YuyangYin** [comment]
No. In our model design, brightness level must be input. So we use a number(batch*1) caluated by GT, compared with LLFLOW, they use per pixel reference. Our setting is that if we can know the output brightness level, we can achieve good results.

**Comment by GitKing-Wu** [comment]
Thank you very much for your answer. Can this brightness level be manually designed in the absence of GT?

**Comment by YuyangYin** [comment]
It is a good question. We try to use a simple mlp to predict normal image level, but the overfitting problems occures. I guess the normal light level is determined by hands with different cammera setting. The another problem is if we use brightness level predicted by a mlp. The psnr is high effected by brighness level. For example, two image with different level but have the same detail quailty. The best psnr is the level which matchs GT best. I think is unfair, so we add a LI-LPIPS.

**Comment by GitKing-Wu** [comment]
I understand. Thank you again for your reply

**Comment by RenzhiHu111** [comment]
brightness_level=gt_image.mean([1, 2, 3]) # b*1
sampledImgs = sampler(lowlight_image, data_concate,brightness_level,ddim=True,
                      unconditional_guidance_scale=1,ddim_step=config.ddim_step)/////

It is common sense that in the testing phase, no gt should be involved. How to test without gt?

**Comment by YuyangYin** [comment]
> brightness_level=gt_image.mean([1, 2, 3]) # b*1 sampledImgs = sampler(lowlight_image, data_concate,brightness_level,ddim=True, unconditional_guidance_scale=1,ddim_step=config.ddim_step)/////
> 
> It is common sense that in the testing phase, no gt should be involved. How to test without gt?

You can set training dataset mean values of brightness level.
