### ISSUE TITLE
您好，请问 train_mask 训练的时候，为什么 mask_generation 是随机生成 mask，跟需要增强的数据集，比如LOL没有关系吗

### ISSUE THREAD

**Issue by woaiwojia4816294** [YuyangYin/CLEDiffusion#13]
同时，这个 mask 的尺寸也和数据集无关吗

**Comment by YuyangYin** [comment]
oo,感谢关注。设计初衷是认为在inference的时候mask是不规则的，所以最好在训练的时候也见过不规则的mask，因此采用了随机的脚本。至于你说的尺寸、数据集的关联，我们没有做过对比实验去深究

**Comment by woaiwojia4816294** [comment]
感谢回复，看您的代码，您这里说的不规则的 mask是跟训练数据集完全无关的。就是假设你需要增强的是一副图像左下角的猴子，但实际上随机生成的mask是在右上角的一个圆形。这样一组匹配用来训练模型，对模型的性能没有影响吗？

**Comment by YuyangYin** [comment]
可以理解成 在训练过程增强区域是随机生成的，推理过程区域是用户给定的，因为训练过程见过了大量的随机区域增强，所以在推理时可以适配任何形状的mask。换句话说训练的本质，就是让模型理解mask的意义，知道mask内是要调整的，所以mask和数据集无关。不知道我这样是否让你更好理解一些

**Comment by woaiwojia4816294** [comment]
理解了，感谢您的回复
