### ISSUE TITLE
关于消融实验的问题

### ISSUE THREAD

**Issue by MrWan001** [YuyangYin/CLEDiffusion#7]
你好，请问可以公布训练代码吗。
还有关于消融实验部分我有一些问题，Only Lsimple这个损失的效果并不好，PSNR为8.85。
![image](https://github.com/YuyangYin/CLEDiffusion/assets/126931904/5c524e5c-57aa-4b0e-a0d5-9563c15a8aca)
后面具体是哪一点改进让效果提升很大，Only concat x这一组用的是什么损失函数，再concat颜色图和SNR图会有提升吗。

您3.5部分提出的多个损失函数，还有concat颜色图和SNR图，这些改进点在指标上具体会有什么提升，哪一个改进起到作用，我觉得这是一些很有意义的改进，但是在消融实验中没能看出来具体哪个改进起到作用，期待您的解答！

**Comment by YuyangYin** [comment]
我们最初的动机是直接把diffusion的框架用在low light的任务上，即输入low+noised gt，预测normal  light，loss用diffusion原始的预测noise的mse损失。我们和文章LLDiffusion: Learning Degradation Representations in Diffusion Models for Low-Light Image Enhancement有同样的发现，如果只是简单的使用上述框架，效果会非常差，不仅不能有效增亮而且有严重的色偏。基于此我们希望通过辅助损失函数进行调整，针对性的提出了颜色、亮度、结构损失等。
concat snr和color map的设定是希望给去噪过程提供更多信息，相对于原始只有low light image信息，我们发现concat之后能一定程度提升去噪和解决色偏的能力。
对于你说的哪个是核心作用，我认为是辅助损失函数显著提升了指标，达到了和目前方法接近的水平。当然也有可能是我们的diffusion框架设计的不够好，可以参考一下其他同期的类似模型。
最后我们paper其实主要想report的点不是说该框架在某几个数据集上可以达到sota，而是主要想强调给出了可控亮度生成的视角。
如果还有其他问题，欢迎随时交流。

**Comment by MrWan001** [comment]
好的！感谢回复，代码什么时候可以公布哈
