### ISSUE TITLE
关于亮度控制问题

### ISSUE THREAD

**Issue by Wlllllllly** [YuyangYin/CLEDiffusion#8]
您好，我想询问一下，文章中说“extract the vanilla brightness level 𝜆 of normal-light images by calculating the average pixel value”，所以这个brightness level 𝜆是个定值对吗？但是为什么我在(https://yuyangyin.github.io/CLEDiffusion/)，会看到𝜆 low1, 𝜆 low2到𝜆 high2呢？可以再麻烦您介绍一下连续的亮度控制是怎么实现的吗？

**Comment by YuyangYin** [comment]
low1,low2其实就是想表达可以插入不同的亮度等级，对于给定的任意亮度等级可以输出对应的图片，但每次给定的level应该是个常数。连续控制主要借助了插值，在3.3的第二段有详细讲，本质上就是原来比如n行的矩阵只能代表n个feature vector，现在用插值后可以得到任意多个vector，用来代替连续控制的亮度等级。
