### ISSUE TITLE
作者您好！想请问损失函数的细节问题

### ISSUE THREAD

**Issue by MrWan001** [YuyangYin/CLEDiffusion#9]
想请问一下作者损失函数具体是怎么实现的，文中用的SSIM损失等描述是用估计的去噪图像y0和GT做损失，训练过程中U-Net的预测结果是一个噪声，然后采样得到yt-1，是直接用这个yt-1和GT做损失吗，还是说在这些中间步骤就直接预测y0。有点不太明白，期待您的回复！非常感谢！

**Comment by YuyangYin** [comment]
使用中间步骤直接预测y0，用的就是diffusion基础的推y0公式，预测噪声和预测y0是两种常见的diffusion设计形式，我们根据loss的性质两个都做了。

**Comment by MrWan001** [comment]
好的好的，感谢！期待直接看代码学习，哈哈

**Comment by YuyangYin** [comment]
大部分代码已经更新完成，感谢您的关注。
